Src/EndPoints/Web/Pages/Profile/ChangePassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using UserModule.Core.Commands.Users.ChangePassword;
using UserModule.Core.Services;

namespace Web.Pages.Profile
{
    [BindProperties]
    public class ChangePasswordModel : BaseRazor
    {
        private IUserFacade _userFacade;

        public ChangePasswordModel(IUserFacade userFacade)
        {
            _userFacade = userFacade;
        }

        [Display(Name = "کلمه عبور فعلی")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [DataType(DataType.Password)]
        public string CurrentPassword { get; set; }

        [Display(Name = "کلمه عبور جدید")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [DataType(DataType.Password)]

        public string NewPassword { get; set; }


        [Display(Name = "تکرار کلمه عبور جدید")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [Compare("NewPassword", ErrorMessage = "کلمه های عبور یکسان نیستند")]
        [DataType(DataType.Password)]
        public string ConfirmNewPassword { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var result = await _userFacade.ChangePassword(new ChangeUserPasswordCommand()
            {
                CurrentPassword = CurrentPassword,
                NewPassword = NewPassword,
                UserId = User.GetUserId()
            });
            return RedirectAndShowAlert(result, RedirectToPage("Index"));

        }
    }
}

Src/EndPoints/Web/Pages/Profile/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Commands.Users.Edit;
using UserModule.Core.Services;

namespace Web.Pages.Profile
{
    [BindProperties]
    public class EditModel : BaseRazor
    {
        private IUserFacade _userFacade;

        public EditModel(IUserFacade userFacade)
        {
            _userFacade = userFacade;
        }

        [Display(Name = "نام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Name { get; set; }

        [Display(Name = "نام خانوادگی")]
        [Required(ErrorMessage = "{0} را وارد کنید")]

        public string Family { get; set; }


        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public async Task OnGet()
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            if (user != null)
            {
                Name = user.Name;
                Family = user.Family;
                Email = user.Email;
            }
        }

        public async Task<IActionResult> OnPost()
        {
            var result = await _userFacade.EditUserProfile(new EditUserCommand()
            {
                Name = Name,
                Family = Family,
                Email = Email,
                UserId = User.GetUserId()
            });
            return RedirectAndShowAlert(result, RedirectToPage("Index"));
        }
    }
}

Src/EndPoints/Web/Pages/Profile/Index.cshtml.cs
using Web.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Queries._DTOs;
using UserModule.Core.Services;

namespace Web.Pages.Profile
{
    public class IndexModel : PageModel
    {
        private IUserFacade _userFacade;
        private INotificationFacade _notificationFacade;
        public IndexModel(IUserFacade userFacade, INotificationFacade notificationFacade)
        {
            _userFacade = userFacade;
            _notificationFacade = notificationFacade;
        }


        public List<NotificationFilterData> NewNotification { get; set; }
        public UserDto UserDto { get; set; }
        public async Task OnGet()
        {
            UserDto = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            var result = await _notificationFacade.GetByFilter(new NotificationFilterParams()
            {
                IsSeen = false,
                PageId = 1,
                Take = 5,
                UserId = UserDto!.Id
            });
            NewNotification = result.Data;
        }

    }
}

Src/EndPoints/Web/Pages/Profile/Notifications.cshtml.cs
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserModule.Core.Commands.Notifications.Delete;
using UserModule.Core.Commands.Notifications.DeleteAll;
using UserModule.Core.Commands.Notifications.Seen;
using UserModule.Core.Queries._DTOs;
using UserModule.Core.Services;

namespace Web.Pages.Profile
{
    public class NotificationsModel : BaseRazorFilter<NotificationFilterParams>
    {
        private INotificationFacade _notificationFacade;

        public NotificationsModel(INotificationFacade notificationFacade)
        {
            _notificationFacade = notificationFacade;
        }

        public NotificationFilterResult FilterResult { get; set; }
        public async Task OnGet()
        {
            FilterResult = await _notificationFacade.GetByFilter(new NotificationFilterParams()
            {
                IsSeen = null,
                PageId = FilterParams.PageId,
                Take = 6,
                UserId = User.GetUserId()
            });
        }

        public async Task<IActionResult> OnPostSeenNotification(Guid notificationId)
        {
            var result = await _notificationFacade.Seen(new SeenNotificationCommand(notificationId));
            return RedirectAndShowAlert(result, RedirectToPage("Notifications"));
        }
        public async Task<IActionResult> OnPostDeleteAll()
        {
            return await AjaxTryCatch(() => _notificationFacade.DeleteAll(new DeleteAllNotificationCommand(User.GetUserId())));
        }
        public async Task<IActionResult> OnPostDeleteNotification(Guid id)
        {
            return await AjaxTryCatch(() => _notificationFacade.Delete(new DeleteNotificationCommand(id, User.GetUserId())));
        }
    }
}

Src/EndPoints/Web/Pages/Profile/Tickets/Add.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace Web.Pages.Profile.Tickets
{
    [BindProperties]
    public class AddModel : BaseRazor
    {
        private IUserFacade _userFacade;
        private ITicketService _ticketService;

        public AddModel(IUserFacade userFacade, ITicketService ticketService)
        {
            _userFacade = userFacade;
            _ticketService = ticketService;
        }

        [Display(Name = "عنوان تیکت")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "متن تیکت")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            var command = new CreateTicketCommand()
            {
                PhoneNumber = user.PhoneNumber,
                OwnerFullName = $"{user.Name} {user.Family}",
                Text = Text,
                Title = Title,
                UserId = user.Id
            };
            var result = await _ticketService.CreateTicket(command);

            return RedirectAndShowAlert(result, RedirectToPage("Index"));
        }
    }
}

Src/EndPoints/Web/Pages/Profile/Tickets/Index.cshtml.cs
using AngleSharp.Dom;
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;

namespace Web.Pages.Profile.Tickets
{
    public class IndexModel : BaseRazorFilter<TicketFilterParams>
    {
        private ITicketService _ticketService;

        public IndexModel(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public TicketFilterResult FilterResult { get; set; }
        public async Task OnGet()
        {
            FilterResult = await _ticketService.GetTicketsByFilter(new TicketFilterParams()
            {
                UserId = User.GetUserId(),
                Take = 10,
                PageId = FilterParams.PageId
            });
        }
    }
}

Src/EndPoints/Web/Pages/Profile/Tickets/Show.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Common.Application;
using Web.Infrastructure;
using Web.Infrastructure.RazorUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketModule.Core.DTOs.Tickets;
using TicketModule.Core.Services;
using UserModule.Core.Services;

namespace Web.Pages.Profile.Tickets
{
    public class ShowModel : BaseRazor
    {
        private ITicketService _ticketService;
        private IUserFacade _userFacade;
        public ShowModel(ITicketService ticketService, IUserFacade userFacade)
        {
            _ticketService = ticketService;
            _userFacade = userFacade;
        }

        public TicketDto Ticket { get; set; }


        [BindProperty]
        [Display(Name = "متن پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Text { get; set; }
        public async Task<IActionResult> OnGet(Guid ticketId)
        {
            var ticket = await _ticketService.GetTicket(ticketId);
            if (ticket == null || ticket.UserId != User.GetUserId())
                return RedirectToPage("Index");


            Ticket = ticket;
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid ticketId)
        {
            var user = await _userFacade.GetUserByPhoneNumber(User.GetPhoneNumber());
            var message = new SendTicketMessageCommand()
            {
                OwnerFullName = $"{user.Name} {user.Family}",
                Text = Text,
                TicketId = ticketId,
                UserId = User.GetUserId()
            };
            var result = await _ticketService.SendMessageInTicket(message);
            return RedirectAndShowAlert(result, RedirectToPage("Show", new { ticketId }));
        }


        public async Task<IActionResult> OnPostCloseTicket(Guid ticketId)
        {
            return await AjaxTryCatch(async () =>
            {
                var ticket = await _ticketService.GetTicket(ticketId);
                if (ticket == null || ticket.UserId != User.GetUserId())
                    return OperationResult.Error("تیکت یافت نشد");

                return await _ticketService.CloseTicket(ticketId);
            });
        }
    }
}

Src/EndPoints/Web/Pages/Profile/ChangePassword.cshtml
@page
@model ChangePasswordModel
@section meta
    {
    <link rel="stylesheet" href="/css/profile.min.css">
}
<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 breadcrumb">
                <ul class="">
                    <li>
                        <a href="/">
                            خانه
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a href="/profile">
                            پنل کاربری
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a class="current">
                            تغییر کلمه عبور
                        </a>
                    </li>
                </ul>

            </div>
            <partial name="Shared/_ProfileSideBar" />
            <div class="col-12 col-xl-9 col-lg-9 col-md-8 profile-body">
                <div class="row ">
                    <div class="col-12 info shadow pl-0 pr-0">
                        <p class="title">
                            <i class="fa fa-address-card-o"></i>
                            ویرایش اطلاعات پروفایل
                        </p>
                        <div class="info-body p-2">
                            <form method="post" class="row">
                                <div class="col-12">
                                    @Html.EditorFor(f=>f.CurrentPassword)
                                </div>
                                <div class="col-12 col-lg-6 col-md-6 mb-3">
                                    @Html.EditorFor(f=>f.NewPassword)
                                </div>
                                <div class="col-12 col-lg-6 col-md-6 mb-3">
                                    @Html.EditorFor(f=>f.ConfirmNewPassword)

                                </div>
                                <div class="col-12">
                                    <button class="btn  btn-save  mt-3">تغییر کلمه عبور </button>

                                </div>
                            </form>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</main>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

                                    }

Src/EndPoints/Web/Pages/Profile/Edit.cshtml
@page
@model EditModel
@section meta
    {
    <link rel="stylesheet" href="/css/profile.min.css">
}
<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 breadcrumb">
                <ul class="">
                    <li>
                        <a href="/">
                            خانه
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a href="/profile">
                            پنل کاربری
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a class="current">
                            ویرایش حساب کاربری
                        </a>
                    </li>
                </ul>

            </div>
            <partial name="Shared/_ProfileSideBar" />
            <div class="col-12 col-xl-9 col-lg-9 col-md-8 profile-body">
                <div class="row ">
                    <div class="col-12 info shadow pl-0 pr-0">
                        <p class="title">
                            <i class="fa fa-address-card-o"></i>
                            ویرایش اطلاعات پروفایل
                        </p>
                        <div class="info-body p-2">
                            <form method="post" class="row">
                                <div class="col-12 col-lg-6 col-md-6 mb-3">
                                    @Html.EditorFor(f=>f.Name)
                                </div>
                                <div class="col-12 col-lg-6 col-md-6 mb-3">
                                    @Html.EditorFor(f=>f.Family)

                                </div>
                                <div class="col-12">
                                    @Html.EditorFor(f=>f.Email)
                                </div>

                                <div class="col-12">
                                    <button class="btn  btn-save  mt-3">ویرایش اطلاعات</button>

                                </div>
                            </form>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</main>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

                                    }

Src/EndPoints/Web/Pages/Profile/Index.cshtml
@page
@using Common.Application
@model IndexModel
@section meta
    {
    <link rel="stylesheet" href="/css/profile.min.css">
}
<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 breadcrumb">
                <ul class="">
                    <li>
                        <a href="/">
                            خانه
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a class="current">
                            پنل کاربری
                        </a>
                    </li>
                </ul>

            </div>
            <partial name="Shared/_ProfileSideBar" />
            <div class="col-12 col-xl-9 col-lg-9 col-md-8 profile-body">
                <div class="row ">
                    <div class="col-12 col-lg-6 col-xl-6 ">
                        <div class="info custom-shadow">

                            <p class="title">
                                <i class="fa fa-address-card-o"></i>
                                اطلاعات حساب
                            </p>

                            <div class="info-body p-2">
                                <div>
                                    <p>نام و نام خانوادگی : محمد اشرافی</p>
                                </div>
                                <div>
                                    <p>ایمیل : <label>game.bikar@gmail.com</label></p>
                                </div>
                                <div>
                                    <p>شماره تلفن : 09351171196</p>
                                </div>
                                <div>
                                    <p> کد ملی : </p>
                                </div>
                                <a href="#" class="btn btn-info btn-block">تکمیل اطلاعات </a>
                            </div>
                        </div>

                    </div>
                    <div class="col-12 col-xl-6 col-lg-6 ">
                        <div class="notifications shadow">
                            <p class="title">
                                <i class="zmdi zmdi-notifications-active"></i>
                                آخرین پیغام
                            </p>
                            <div class="notification-body p-1">
                                @if (Model.NewNotification.Any())
                                {
                                    foreach (var item in Model.NewNotification)
                                    {
                                        <div class="item pb-3">
                                            <h6 class="mb-0 mt-1">@item.Title</h6>
                                            <hr />
                                            <p>@Html.Raw(item.Text)</p>
                                            <span class="pull-left">@item.CreationDate.ToPersianDateTime()</span>
                                        </div>
                                    }

                                    <a asp-page="Notifications" class="btn btn-info btn-block">نمایش همه</a>
                                }
                                else
                                {
                                    <div class="no-item text-center">
                                        <p>
                                            <i class="fa fa-info text-info"></i>
                                            موردی برای نمایش وجود ندارد
                                        </p>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                    <div class="col-12 mt-4">
                        <div class="favorites shadow">
                            <p class="title">
                                <i class="fa fa-heart text-danger"></i>
                                علاقه مندی ها
                            </p>
                            <div class="favorites-body">
                                <div class="item">
                                    <img src="images/course.jpg" alt="">
                                    <a href="#" class="item-title">
                                        دوره آموزش برنامه نویسی Asp.NetCore به همراه پروژه عملی
                                    </a>
                                    <p class="tools">
                                        <i class="fa fa-trash text-danger" title="حذف"
                                           data-toggle="tooltip"></i>
                                    </p>
                                </div>
                                <div class="item">
                                    <img src="images/Course/4.jpg" alt="">
                                    <a href="#" class="item-title">
                                        دوره آموزش برنامه نویسی Asp.NetCore به همراه پروژه عملی
                                    </a>
                                    <p class="tools">
                                        <i class="fa fa-trash text-danger" title="حذف"
                                           data-toggle="tooltip"></i>
                                    </p>
                                </div>
                                <div class="item">
                                    <img src="images/Course/2.png" alt="">
                                    <a href="#" class="item-title">
                                        آموزش رایگان nextJs
                                    </a>
                                    <p class="tools">
                                        <i class="fa fa-trash text-danger" title="حذف"
                                           data-toggle="tooltip"></i>
                                    </p>
                                </div>
                                <!-- <div class="no-item text-center">
                                    <p>
                                        <i class="fa fa-info text-info"></i>
                                        موردی برای نمایش وجود ندارد
                                    </p>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

Src/EndPoints/Web/Pages/Profile/Notifications.cshtml
@page "{handler?}"
@using Common.Application
@model NotificationsModel
@section meta
    {
    <link rel="stylesheet" href="/css/profile.min.css">
}
@{
    ViewData["title"] = "پیغام ها";
}
<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 breadcrumb">
                <ul class="">
                    <li>
                        <a href="/">
                            خانه
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a href="/profile">
                            پنل کاربری
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    <li>
                        <a class="current">
                            @ViewData["title"]
                        </a>
                    </li>
                </ul>

            </div>
            <partial name="Shared/_ProfileSideBar" />
            <div class="col-12 col-xl-9 col-lg-9 col-md-8 profile-body">
                <div class="info shadow pl-0 pr-0">
                    <p class="title">
                        <i class="zmdi zmdi-notifications text-warning"></i>
                        @ViewData["title"]
                        <delete-item is-button-tag="false" class="pull-left pointer" data-toggle="tooltip" title="حذف همه"
                                     url="@Url.Page("Notifications","DeleteAll")">
                            <i class="fa fa-trash-o text-danger" style="font-size: 25px;"></i>
                        </delete-item>

                    </p>

                    <div class="info-body ">
                        <div class="table-responsive">
                            <table class="table text-center  table-hover  table-striped text-center">
                                <thead>
                                    <tr>
                                        <th>متن</th>
                                        <th>وضعیت</th>
                                        <th>تاریخ</th>
                                        <td>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.FilterResult.Data)
                                    {
                                        <tr>
                                            <td>
                                                <p><b>@item.Title</b></p>
                                                <p>
                                                    @item.Text
                                                </p>
                                            </td>
                                            <td>
                                                @if (item.IsSeen)
                                                {
                                                    <span class="badge badge-success">مشاهده شده</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-danger">جدید</span>
                                                }
                                            </td>
                                            <td>
                                                @item.CreationDate.ToPersianDateTime()
                                            </td>
                                            <td>
                                                @if (item.IsSeen == false)
                                                {
                                                    <form method="post" asp-page-handler="SeenNotification" class="d-inline-block">
                                                        <input type="hidden" name="notificationId" value="@item.Id" />
                                                        <button class="btn btn-success btn-sm" data-toggle="tooltip" title="این پیام خواندم" onclick="return confirm('آیا از انجام عملیات اطمینان دارید ؟')">
                                                            <i class="fa fa-check text-white"></i>
                                                        </button>
                                                    </form>
                                                }
                                                <delete-item url="@Url.Page("Notifications", "DeleteNotification", new { id = item.Id })" data-toggle="tooltip" title="حذف" class=" btn btn-sm btn-danger">
                                                    <i class="fa fa-trash"></i>
                                                </delete-item>
                                            </td>
                                        </tr>
                                    }
                                    @if (Model.FilterResult.EntityCount == 0)
                                    {
                                        <tr>
                                            <td colspan="4">موردی برای نمایش وجود ندارد</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <partial name="Shared/_Pagination" model="Model.FilterResult" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>